server.port: 5000

localeTag: ru-RU

logging:
  level:
    root: info
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  file:
    path: /logs/bot

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:qwerty}
    hikari:
      poolName: Hikari
      auto-commit: false
  jpa:
    database: POSTGRESQL
    show-sql: true

telegrambot:
  userName: To_Check_Price_Bot
  botToken: ${TOKEN_KEY:null}
  webHookPath: https://checkingpricebot.herokuapp.com/

subscriptions.processPeriod: 1800000

pattern.url: https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b([-a-zA-Z0-9()@:%_\+.~#?&//=]*)